language: python
python:
#  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  #- "3.7" #image not available
  #- "3.7-dev"  # tf not available through pip
# command to install dependencies
install:
  - pip install -r dev-requirements.txt
# command to run tests
script:
  - pytest --ignore models
  - python ./deeprace.py help
